[package]
name = "meet-in-the-middle-discrete-log"
version = "0.1.0"
authors = ["Filip Kubiš <filip.kubis@datasentics.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.12.0"