[package]
name = "chunk-hashing"
version = "0.1.0"
authors = ["Filip Kubiš <filip.kubis@datasentics.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.4.2"
hex = "0.3.0"