[package]
name = "cbc-decryption"
version = "0.1.0"
authors = ["Filip Kubiš <filip.kubis@datasentics.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.7.1"
hex = "0.4.3"